changed -O parsing code to allow comma(,) escaping
now it's possible for values passed to -O to contain escaped commas

diff --git a/plugins/check-connectivity/check-connectivity b/plugins/check-connectivity/check-connectivity
--- a/plugins/check-connectivity/check-connectivity
+++ b/plugins/check-connectivity/check-connectivity
@@ -117,15 +117,36 @@ while getopts $getopt_flags OPTNAME; do
       disable_cache=1
       ;;
     O)
-      IFS=, read -a received_options <<< "$OPTARG"
-      for name_val in "${received_options[@]}"; do
-        if ! [[ "$name_val" =~ ^([A-Za-z0-9_]+)=(.+) ]]; then
-          warn "skipping invalid option '$name_val'"
+      prev_char=""
+      name_value=""
+      declare -i n_pos=0
+      while [ $n_pos -lt ${#OPTARG} ]; do
+        char=${OPTARG:$n_pos:1}
+        n_pos+=1
+        if [ "$char" == "," ] && [ -z "$name_value" -o -z "$prev_char" ]; then
+          continue
+        elif [ "$char" == "," -a "$prev_char" != "\\" -a "$prev_char" != "," ]; then
+          received_options+=( "$name_value" )
+          name_value=""
+          prev_char=""
+        elif [ "$char" == "," -a "$prev_char" == "\\" ]; then
+          name_value="${name_value:0:$(( $n_pos - 1 ))},"
+          prev_char="$char"
+        else
+          name_value+="$char"
+          prev_char="$char"
+        fi
+      done
+      [ -n "$name_value" ] && received_options+=("$name_value")
+
+      for name_value in "${received_options[@]}"; do
+        if ! [[ "$name_value" =~ ^([A-Za-z0-9_]+)=(.+) ]]; then
+          warn "skipping invalid option '$name_value'"
           continue
         fi
 
-        opt_name=${name_val%%=*}
-        opt_value=${name_val#*=}
+        opt_name=${name_value%%=*}
+        opt_value=${name_value#*=}
 
         if is_in_array "$opt_name" ${accepted_opt_names[@]}; then
           eval "$opt_name"=\""$opt_value"\"
@@ -133,7 +154,7 @@ while getopts $getopt_flags OPTNAME; do
           warn "skipping invalid option name '$opt_name'"
         fi
       done
-        ;;
+      ;;
     *)
       exit $NAGIOS_UNKNOWN
       ;;
